### ISSUE TITLE
f.flashloan returns error

### ISSUE THREAD

**Issue by Ljtron** [mrdavey/ez-flashloan#3] opened 2020-04-05 20:13 UTC
I have a problem every time I run await f.flashloan() in 
ganache-cli forking from the main network 
I get this error

Thrown:
Error: Returned error: VM Exception while processing transaction: revert    at PromiEvent (C:\Users\Ljtro\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\contract\lib\promievent.js:9:1)
    at TruffleContract.flashloan (C:\Users\Ljtro\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\contract\lib\execute.js:169:1)
    at evalmachine.<anonymous>:1:11
    at evalmachine.<anonymous>:2:49
    at sigintHandlersWrap (vm.js:269:15)
    at Script.runInContext (vm.js:124:14)
    at runScript (C:\Users\Ljtro\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\core\lib\console.js:222:1)
    at Console.interpret (C:\Users\Ljtro\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\core\lib\console.js:237:1)
    at ReplManager.interpret (C:\Users\Ljtro\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\core\lib\repl.js:131:1)
    at bound (domain.js:419:14)
    at REPLServer.runBound [as eval] (domain.js:432:12)
    at REPLServer.onLine (repl.js:715:10)
    at REPLServer.emit (events.js:210:5)
    at REPLServer.EventEmitter.emit (domain.js:475:20)
    at REPLServer.Interface._onLine (readline.js:316:10)
    at REPLServer.Interface._line (readline.js:693:8)
    at REPLServer.Interface._ttyWrite (readline.js:1019:14)
    at REPLServer.self._ttyWrite (repl.js:792:7)
    at ReadStream.onkeypress (readline.js:191:10)
    at ReadStream.emit (events.js:210:5)
    at ReadStream.EventEmitter.emit (domain.js:475:20)
    at emitKeys (internal/readline/utils.js:433:14)
    at emitKeys.next (<anonymous>)
    at ReadStream.onData (readline.js:1153:36)
    at ReadStream.emit (events.js:210:5)
    at ReadStream.EventEmitter.emit (domain.js:475:20)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11) {
  hijackedStack: 'Error: Returned error: VM Exception while processing transaction: revert\n' +
    '    at Object.ErrorResponse (C:\\Users\\Ljtro\\AppData\\Roaming\\npm\\node_modules\\truffle\\build\\webpack:\\node_modules\\web3-core-helpers\\src\\errors.js:29:1)\n' +
    '    at C:\\Users\\Ljtro\\AppData\\Roaming\\npm\\node_modules\\truffle\\build\\webpack:\\node_modules\\web3-core-requestmanager\\src\\index.js:140:1\n' +
    '    at C:\\Users\\Ljtro\\AppData\\Roaming\\npm\\node_modules\\truffle\\build\\webpack:\\packages\\provider\\wrapper.js:112:1\n' +
    '    at XMLHttpRequest.request.onreadystatechange (C:\\Users\\Ljtro\\AppData\\Roaming\\npm\\node_modules\\truffle\\build\\webpack:\\node_modules\\web3-providers-http\\src\\index.js:96:1)\n' +
    '    at XMLHttpRequestEventTarget.dispatchEvent (C:\\Users\\Ljtro\\AppData\\Roaming\\npm\\node_modules\\truffle\\build\\webpack:\\node_modules\\xhr2-cookies\\dist\\xml-http-request-event-target.js:34:1)\n' +
    '    at XMLHttpRequest._setReadyState (C:\\Users\\Ljtro\\AppData\\Roaming\\npm\\node_modules\\truffle\\build\\webpack:\\node_modules\\xhr2-cookies\\dist\\xml-http-request.js:208:1)\n' +
    '    at XMLHttpRequest._onHttpResponseEnd (C:\\Users\\Ljtro\\AppData\\Roaming\\npm\\node_modules\\truffle\\build\\webpack:\\node_modules\\xhr2-cookies\\dist\\xml-http-request.js:318:1)\n' +
    '    at IncomingMessage.<anonymous> (C:\\Users\\Ljtro\\AppData\\Roaming\\npm\\node_modules\\truffle\\build\\webpack:\\node_modules\\xhr2-cookies\\dist\\xml-http-request.js:289:47)\n' +
    '    at IncomingMessage.emit (events.js:215:7)\n' +
    '    at IncomingMessage.EventEmitter.emit (domain.js:498:23)\n' +
    '    at endReadableNT (_stream_readable.js:1184:12)\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:80:21)'

**Comment by mrdavey** [comment] 2020-04-06 09:15
Hm... i'm not sure what the issue is there, however have you tried starting again and pulling the latest updates from Git? I recently updated the repo and haven't had any problems with it so far.

Also make sure you read the entire README.MD as there are instructions on how to set up properly, as well as how to debug errors.

**Comment by Ljtron** [comment] 2020-04-07 15:03
I did what you said and started over than My contract reverted again but the reason was 

_**SafeERC20: low-level call failed**_

 
do you know how to solve this error

**Comment by mrdavey** [comment] 2020-04-07 16:25
Yes that means something went wrong in your ERC20 call, either when transferring or checking balances. You will need to double check all your contract balances and ensure you have enough of what you are trying to send.

**Closed by mrdavey** 2020-04-07 16:25 UTC

**Comment by Ljtron** [comment] 2020-04-07 16:53
I'm still getting the same error even though I am filling up the smart contract with 20 ether worth of dai and 5 ether and I'm only requesting 1 ether worth of dai from the flash loan.
